add solution for lection-3 task-2 (modal)
js-tasks-ru/htmlcss-20211021_barkadron pull request #11
Opened 2021-11-08 21:52 UTC by barkadron

2021-11-08 21:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-10 20:54 UTC, GSemikozov requested changes

2021-11-10 20:54 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__backdrop {
backdrop в этой иерархии будет лишним, полупрозрачный фон можно задать сразу на .modal

2021-11-10 20:54 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal {
модалку нужно позиционировать относительно окна браузера, причем при такой структуре компонента блок должен растягиваться на 100vh + 100vw (и иметь полупрозрачный фон)

2021-11-10 20:54 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    height: 70%;
вот это здесь лишнее

2021-11-10 20:54 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__window {
а само окно можно позиционировать по центру абсолютом (ну или через родителя привычным способом через флекс или грид)

2021-11-10 20:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-11 20:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-11 21:44 UTC, barkadron commented on 05-lection3/02-modal/modal.css
> +.modal__backdrop {
убрал в fe348ef

2021-12-11 21:45 UTC, barkadron commented on 05-lection3/02-modal/modal.css
> +.modal {
исправил в fe348ef

2021-12-11 21:45 UTC, barkadron commented on 05-lection3/02-modal/modal.css
> +    height: 70%;
исправил в fe348ef

2021-12-11 21:45 UTC, barkadron commented on 05-lection3/02-modal/modal.css
> +.modal__window {
Почему-то мне казалось, что лучше не по центру, а чуть-чуть выше, пытался это изобразить :)
Исправил в fe348ef

2021-12-11 21:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-14 20:15 UTC, GSemikozov approved these changes

2021-12-14 20:16 UTC, merged