add solution for lection-1 task-2 (accordion)
js-tasks-ru/htmlcss-20211021_barkadron pull request #4
Opened 2021-11-04 22:19 UTC by barkadron

2021-11-04 22:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-05 14:48 UTC, GSemikozov requested changes

2021-11-05 14:48 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
здесь на уровне блока не будем фиксировать размеры (ширины и высоты)

2021-11-05 14:48 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    float: right; /* вроде как плохо, но пока только так :) */
мы ведь уже знаем flexbox и grid, заччем такие сложности с отжившими свое свойствами )

2021-11-05 15:48 UTC, barkadron commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
убрал

2021-11-05 15:51 UTC, barkadron commented on 03-lection1/02-accordion/accordion.css
> +    float: right; /* вроде как плохо, но пока только так :) */
Думал, что раз эта задача до того, как прошли flex, то нужно без него делать или вообще не делать 😄 
Переделал на flex + поправил шрифты (изначально не заметил, что рендерится не тот шрифт). 514dd95

2021-11-06 19:49 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    float: right; /* вроде как плохо, но пока только так :) */
отлично!)

2021-11-06 19:50 UTC, GSemikozov approved these changes

2021-11-06 19:50 UTC, merged